###
GET http://localhost:5000/employee

###
GET http://localhost:5000/employee?role=Carpentiere

###
GET http://localhost:5000/employee/66eee0632541693376d243bb

###
PUT http://localhost:5000/employee/66eee0632541693376d243bb
Content-Type: application/json

{
    "role": "addetto alle operazioni di magazzino"
}

###
DELETE http://localhost:5000/employee/66ec432ef04045e5956879e7