###
POST http://localhost:5000/api/v1/profile/66fac23c83e921f8e573299b/employee/66fac23c83e921f8e5732999/payEnvelope
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSWQiOiI2NmZhYzIzYzgzZTkyMWY4ZTU3MzI5OWIiLCJpYXQiOjE3Mjc4MDU2NjQsImV4cCI6MTcyNzgwOTI2NH0.bALs2Sfgh9HWMtPgFOvevFuPYa5O3ibiOi_rwasiuUQ
Content-Type: application/json

{
    "companyData": {
        "companyName": "Nome Azienda",
        "vatNumber": "12345678901",
        "IBAN": "IT60X1234567890123456789012"
    },
    "payPeriod": {
        "month": 4,
        "year": 2024,
        "worked": {
            "days": 22,
            "hours": 176
        }
    },
    "salary": {
        "basicSalary": 1800,
        "total": 2300
    },
    "deductions": {
        "taxes": 400,
        "socialContributions": 300,
        "totalDeductions": 750
    },
    "payCheck": 1550
}

###
GET http://localhost:5000/api/v1/payEnvelope?year=2024

###
GET http://localhost:5000/api/v1/employee/66ef094ab2abd62ad9e5ee32/payEnvelope/66ef098eb2abd62ad9e5ee38

###
PUT http://localhost:5000/api/v1/employee/66f271a789d1801f54de0438/payEnvelope/66f271de89d1801f54de043e
Content-Type: application/json

{
  "payPeriod": {
    "month": 3,
    "year": 2023,
    "worked": {
      "days": 22,
      "hours": 160
    }
  }
}

###
DELETE http://localhost:5000/api/v1/employee/66f271a789d1801f54de0438/payEnvelope/66f271de89d1801f54de043e