###
GET http://localhost:5000/profile

###
GET http://localhost:5000/profile/66f1ab4e778da5d539742d8c

###
PUT http://localhost:5000/profile/66ef06658b48d84fa357ded2
Content-Type: application/json

{
    "name": "Enrico",
    "surname": "Ruocco",
    "email": "ruoccoenrico@gmail.com",
    "birthday": 551334800000,
    "avatar": ""
}

###
PUT http://localhost:5000/profile/66ef06658b48d84fa357ded2
Content-Type: application/json

{
    "name": "Giovanni",
    "password": "ruoccogiovanni"
}

###
PUT http://localhost:5000/profile/66ef06658b48d84fa357ded2
Content-Type: application/json

{
  "whoIs": {
    "type": "admin",
    "adminData": {
      "name": "Direttore Tecnico",  
      "description": "Responsabile del reparto tecnico"  
    }
  }
}

###
DELETE http://localhost:5000/profile/66ef07178b48d84fa357dee1