###
GET http://localhost:5000/profile

###
GET http://localhost:5000/profile/672291de13f0823fa4b4806f

###
PUT http://localhost:5000/profile/672291de13f0823fa4b4806f
Content-Type: application/json

{
  "surname": "Ruocco"
}

###
PUT http://localhost:5000/profile/672291de13f0823fa4b4806f
Content-Type: application/json

{
  "password": "andrearuocco"
}

###
DELETE http://localhost:5000/profile/672203515d48da76212b88eb