###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Epicode",
    "email": "andreaepicode@gmail.com",
    "password": "andreaepicode",
    "birthday": 774032800000,
    "avatar": "",
    "IBAN": "IT60X0542811101000000123456",
    "country": "Italy",
    "whoIs": {
        "type": "admin",
        "adminData": {
            "name": "Amministratore Delegato",
            "description": "Amministatore unico di questa bellissima azienda."
        }
    }
}

###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Vincenzo",
    "surname": "Epicode",
    "email": "vincenzoepicode@gmail.com",
    "password": "vincenzoaepicode",
    "birthday": 774032800000,
    "avatar": "",
    "IBAN": "FR60X0542811101000000123456",
    "country": "Italy",
    "whoIs": {
        "type": "employee"
    }
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "vincenzoepicode@gmail.com",
    "password": "vincenzoepicode"
}

###
GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSWQiOiI2NmYyNjFhYzU3YjZjYTY2Mjg1ZDVkMDEiLCJpYXQiOjE3Mjc1MDk0MDAsImV4cCI6MTcyNzUxMzAwMH0.7sai0RsT8KRalFPbb476siw8FbvyWxTtOtvAV9lkkbI
