###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Ruocco",
    "email": "ruoca96@gmail.com",
    "password": "andrearuocco",
    "birthday": 774032800000,
    "avatar": "",
    "IBAN": "IT60X0542811101000000123456",
    "country": "Italy",
    "whoIs": {
        "type": "admin",
        "adminData": {
            "name": "Amministratore Delegato",
            "description": "Direttore di questa bellissima azienda."
        }
    }
}