###
POST http://localhost:5000/companies/672290bf13f0823fa4b48067/profile
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Epicode",
    "email": "andreaepicode@gmail.com",
    "password": "andreaepicode",
    "birthday": 323752800110,
    "IBAN": "IT20Q0300203280561121424713",
    "TIN": "RCCNDR96H17E625S",
    "country": "Italia"
}

###
GET http://localhost:5000/companies/672290bf13f0823fa4b48067/profile

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "andreaepicode@gmail.com",
    "password": "andreaepicode"
}

###
GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSWQiOiI2NzIyOTFkZTEzZjA4MjNmYTRiNDgwNmYiLCJpYXQiOjE3MzAzMTkxMTgsImV4cCI6MTczMDMyMjcxOH0.BDaoaxkrJ_8h7YZq76HmQ-Mqy_gXb-q_XPz1nBVIljk



